//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by c:\Documents and Settings\Big Muscle\Dokumenty\Visual Studio Projects\StrongDC++\StrongDC.rc
//
#define IDD_ABOUTBOX                    100
#define IDC_FILETYPES                   101
#define IDC_TRAY_SHOW                   103
#define IDC_COPY_HUB                    104
#define IDC_CDMDEBUG_WINDOW             106
#define IDD_GENERALPAGE                 107
#define IDR_MAINFRAME                   128
#define IDR_HUB                         129
#define IDC_HUBLIST                     131
#define IDC_SERVER                      133
#define IDC_FILES                       135
#define IDB_FOLDERS                     206
#define IDB_ARROWS                      208
#define IDD_LINE                        209
#define IDB_USERS                       210
#define IDD_ADVANCEDPAGE                210
#define IDD_DOWNLOADPAGE                211
#define IDD_UPLOADPAGE                  212
#define IDB_TOOLBAR                     213
#define IDD_APPEARANCEPAGE              213
#define IDR_PUBLICHUBS                  215
#define IDR_SEARCH                      216
#define IDR_FAVORITES                   217
#define IDR_PRIVATE                     218
#define IDR_DIRECTORY                   219
#define IDR_NOTEPAD                     220
#define IDB_TOOLBAR20                   221
#define IDR_QUEUE                       221
#define IDR_SPY                         222
#define IDD_FAVORITEHUB                 223
#define IDR_USERS                       224
#define IDD_ADVANCED2PAGE               224
#define IDD_USER_COMMAND                230
#define IDR_FINISHED_DL                 231
#define IDR_FINISHED_UL                 232
#define IDR_ADLSEARCH                   233
#define IDD_ADLS_PROPERTIES             234
#define IDB_TOOLBAR20_HOT               235
#define IDD_UCPAGE                      236
#define IDR_NET_STATS                   237
#define IDR_RECENTS                     238
#define IDR_MAINFRAME_XP                240
#define IDB_SPLASH                      240
#define IDR_UPLOAD_QUEUE                241
#define IDD_SOUNDS                      241
#define IDR_PRIVATE_OFF                 242
#define IDR_HUB_OFF                     243
#define IDD_SEGMENT                     243
#define IDB_O_ARROWS                    244
#define IDB_O_SETTINGS_DLG              245
#define IDR_TRANSFER_COMPRESSED         246
#define IDR_TRANSFER_SEGMENTED          247
#define IDD_FAKEDETECT                  248
#define IDD_OPERACOLORS                 249
#define IDD_AVIPREVIEW                  250
#define IDD_PREVIEW                     252
#define IDB_STATE                       254
#define IDB_BITMAP1                     255
#define IDB_O_OTOOLS                    256
#define IDB_SEARCH_ICONS                257
#define IDB_SEARCH_TYPES                257
#define IDD_TOOLBARPAGE                 259
#define IDD_DOWNLOADDIR                 260
#define IDD_DIALOG2                     261
#define IDD_DOWNLOADDIRS                261
#define IDD_CLIENT_PROFILE              263
#define IDD_CLIENTS_PAGE                264
#define IDB_BITMAP3                     266
#define IDB_SPEEDS                      266
#define IDI_ICON1                       269
#define IDR_FINISHED_MP3                269
#define IDC_REFRESH                     1000
#define IDC_NICK                        1001
#define IDC_EMAIL                       1002
#define IDC_DESCRIPTION                 1003
#define IDC_CONNECTION                  1005
#define IDC_USERS                       1006
#define IDC_ACTIVE                      1006
#define IDC_PASSIVE                     1007
#define IDC_PORT                        1008
#define IDC_DIRECTORIES                 1009
#define IDC_REMOVE_ALL                  1010
#define IDC_ADD                         1011
#define IDC_REMOVE                      1012
#define IDC_MP3                         1013
#define IDC_TOTAL                       1014
#define IDC_SLOTS                       1015
#define IDC_SLOTSPIN                    1016
#define IDC_TRANSFERS                   1017
#define IDC_DOWNLOADDIR                 1017
#define IDC_CONNECT                     1018
#define IDC_BROWSEDIR                   1018
#define IDC_RESULTS                     1019
#define IDC_LINE                        1019
#define IDC_EXTRA_SLOTS2                1019
#define IDC_DOWNLOADDIRTO               1020
#define IDC_EXTRASPIN                   1020
#define IDC_PRIVATEMESSAGE              1021
#define IDC_VERSION                     1021
#define IDC_GETLIST                     1022
#define IDC_ROLLBACK                    1022
#define IDC_CLVERSION                   1023
#define IDC_EDIT                        1026
#define IDC_NOTEPAD                     1027
#define IDC_AWAY                        1028
#define IDC_SEARCH_ALTERNATES           1029
#define IDC_SELWINCOLOR                 1031
#define IDC_SELTEXT                     1032
#define IDC_SHAREHIDDEN                 1035
#define IDC_QUEUE                       1037
#define IDC_HUBNICK                     1041
#define IDC_HUBPASS                     1042
#define IDC_NEWFAV                      1042
#define IDC_HUBNAME                     1043
#define IDC_SOURCE_TYPE                 1044
#define IDC_RAW_ONE                     1044
#define IDC_SIZE_TYPE                   1045
#define IDC_RAW_TWO                     1045
#define IDC_RAW_THREE                   1046
#define IDC_HUBDESCR                    1047
#define IDC_HUBADDR                     1048
#define IDC_GRANTSLOT                   1049
#define IDC_RAW_FOUR                    1049
#define IDC_FORCE                       1050
#define IDC_RAW_FIVE                    1050
#define IDC_BUFFERSIZE                  1051
#define IDC_LANGUAGE                    1052
#define IDC_BROWSE                      1053
#define IDC_PUBLIC_HUBS                 1054
#define IDC_THANKS                      1055
#define IDC_DOWNLOADS                   1056
#define IDC_SLOTSSPIN                   1057
#define IDC_MAXSPEED                    1058
#define IDC_SPEEDSPIN                   1059
#define IDC_FAVUSERS                    1060
#define IDC_PROXY                       1060
#define IDC_ADD_TO_FAVORITES            1061
#define IDC_LOG_MAIN_CHAT               1061
#define IDC_LOG_PRIVATE_CHAT            1062
#define IDC_HELP_HOMEPAGE               1063
#define IDC_LOG_DOWNLOADS               1063
#define IDC_LOG_UPLOADS                 1064
#define IDC_LOG_DIRECTORY               1065
#define IDC_BROWSE_LOG                  1066
#define IDC_HELP_DISCUSS                1067
#define IDC_HELP_FAQ                    1069
#define IDC_SEARCH_SPY                  1070
#define IDC_IMPORT_QUEUE                1071
#define IDC_LATEST                      1071
#define IDC_PRIVATE_MESSAGE_BEEP        1072
#define IDC_PRIVATE_MESSAGE_BEEP_OPEN   1073
#define IDC_MIN_UPLOAD_SPEED            1074
#define IDC_SETTINGS_TYPE               1074
#define IDC_MIN_UPLOAD_SPIN             1075
#define IDC_CHEVRON                     1076
#define IDC_OPEN_FILE_LIST              1077
#define IDC_TOTALS                      1077
#define IDC_SEARCH                      1078
#define IDC_RATIO                       1078
#define IDC_POST_DOWNLOAD               1079
#define IDC_CLOSE_WINDOW                1080
#define IDC_POST_UPLOAD                 1080
#define IDC_FIND                        1081
#define IDC_MAIN_CHAT                   1081
#define IDC_NEXT                        1082
#define IDC_PRIVATE_CHAT                1083
#define IDC_FINISHED                    1084
#define IDC_TEMP_DOWNLOAD_DIRECTORY     1084
#define IDC_BROWSETEMPDIR               1085
#define IDC_SOCKS_RESOLVE               1086
#define IDC_PROGRESS_BUMPED             1086
#define IDC_REMOVEALL                   1087
#define IDC_FINISHEDMP3                 1088
#define IDC_SOCKS5                      1089
#define IDC_SOCKS_SERVER                1090
#define IDC_SOCKS_PORT                  1091
#define IDC_SOCKS_USER                  1092
#define IDC_SOCKS_PASSWORD              1093
#define IDC_FREESLOTS                   1094
#define IDC_TTHONLY                     1095
#define IDC_COPY_NICK                   1096
#define IDC_ADVANCED_BOOLEANS           1096
#define IDC_ADD_MENU                    1097
#define IDC_MOVE                        1098
#define IDC_REMOVE_MENU                 1098
#define IDC_MENU_ITEMS                  1099
#define IDC_CHANGE_MENU                 1100
#define IDC_NAME                        1101
#define IDC_COMMAND                     1102
#define IDC_PROGRESS_OVERRIDE           1102
#define IDC_HUB                         1103
#define IDC_PROGRESS_OVERRIDE2          1103
#define IDC_SHUTDOWNTIMEOUT             1104
#define IDC_COMMAND_DESCRIPTION         1105
#define IDC_SETTINGS_ODC_MENUBAR_RIGHT  1105
#define IDC_APPEARANCE_BOOLEANS         1106
#define IDC_SETTINGS_ODC_MENUBAR_LEFT   1106
#define IDC_DEFAULT_AWAY_MESSAGE        1107
#define IDC_MAX_TAB_ROWS                1107
#define IDC_CLOSE_DISCONNECTED          1108
#define IDC_OPEN_FOLDER                 1109
#define IDC_OPEN_FILE                   1110
#define IDC_SETTINGS_ODC_MENUBAR_BUMPED 1110
#define IDC_FILE_ADL_SEARCH             1111
#define IDC_SHUTDOWN                    1112
#define IDC_ADLLIST                     1113
#define IDC_MOVE_UP                     1114
#define IDC_MOVE_DOWN                   1115
#define IDC_HUBUSERDESCR                1116
#define IDC_FINISHED_UL                 1117
#define IDC_SEARCH_STRING               1118
#define IDC_DEST_DIR                    1119
#define IDC_IS_ACTIVE                   1120
#define IDC_MIN_FILE_SIZE               1121
#define IDC_MAX_FILE_SIZE               1122
#define IDC_AUTOQUEUE                   1123
#define IDC_GO_TO_DIRECTORY             1124
#define IDC_MATCH_QUEUE                 1125
#define IDC_JUNK_FILE_SIZE              1127
#define IDC_JUNK_BIN_FILE_SIZE          1128
#define IDC_VIEW_AS_TEXT                1129
#define IDC_JUNK_VOB_FILE_SIZE_FORMAT   1129
#define IDC_PAGE                        1130
#define IDC_JUNK_BIN_FILE_SIZE_FORMAT   1130
#define IDC_NET_STATS                   1131
#define IDC_JUNK_FILE_SIZE_FORMAT       1131
#define IDC_SETTINGS_PERSONAL_INFORMATION 1132
#define IDC_SETTINGS_NICK               1133
#define IDC_IGNORE_JUNK_FILES           1133
#define IDC_SETTINGS_EMAIL              1134
#define IDC_SETTINGS_DESCRIPTION        1135
#define IDC_SETTINGS_ODC_SHUTDOWNTIMEOUT 1135
#define IDC_SETTINGS_CONNECTION_TYPE    1136
#define IDC_SETTINGS_CONNECTION_SETTINGS 1137
#define IDC_SETTINGS_IP                 1138
#define IDC_SETTINGS_PORT               1139
#define IDC_SETTINGS_SOCKS5_IP          1140
#define IDC_SETTINGS_SOCKS5_PORT        1141
#define IDC_SETTINGS_SOCKS5_USERNAME    1142
#define IDC_SETTINGS_SOCKS5_PASSWORD    1143
#define IDC_SETTINGS_DIRECTORIES        1144
#define IDC_SETTINGS_DOWNLOAD_DIRECTORY 1145
#define IDC_SETTINGS_UNFINISHED_DOWNLOAD_DIRECTORY 1146
#define IDC_SETTINGS_DOWNLOAD_LIMITS    1147
#define IDC_SETTINGS_DOWNLOADS_MAX      1148
#define IDC_SETTINGS_DOWNLOADS_SPEED_PAUSE 1149
#define IDC_SETTINGS_SPEEDS_NOT_ACCURATE 1150
#define IDC_SETTINGS_PUBLIC_HUB_LIST    1151
#define IDC_SETTINGS_PUBLIC_HUB_LIST_URL 1152
#define IDC_SETTINGS_PUBLIC_HUB_LIST_HTTP_PROXY 1153
#define IDC_SETTINGS_SHARED_DIRECTORIES 1154
#define IDC_SETTINGS_SHARE_SIZE         1155
#define IDC_SETTINGS_UPLOADS_MIN_SPEED  1156
#define IDC_SETTINGS_UPLOADS_SLOTS      1157
#define IDC_SETTINGS_APPEARANCE_OPTIONS 1159
#define IDC_SETTINGS_DEFAULT_AWAY_MSG   1160
#define IDC_SETTINGS_LANGUAGE_FILE      1161
#define IDC_SETTINGS_REQUIRES_RESTART   1162
#define IDC_SETTINGS_LOGGING            1163
#define IDC_SETTINGS_LOG_DIR            1164
#define IDC_SETTINGS_SOUNDS             1165
#define IDC_SETTINGS_ADVANCED           1166
#define IDC_SETTINGS_ROLLBACK           1167
#define IDC_SETTINGS_CLIENT_VER         1168
#define IDC_SETTINGS_WRITE_BUFFER       1169
#define IDC_SETTINGS_MAX_TAB_ROWS       1170
#define IDC_SETTINGS_USER_MENU          1171
#define IDC_SETTINGS_KB                 1172
#define IDC_SETTINGS_B                  1173
#define IDC_SETTINGS_KBPS               1174
#define IDC_ADD_AS_FAVORITE             1175
#define IDC_SETTINGS_SEPARATOR          1194
#define IDC_SETTINGS_RAW                1195
#define IDC_SETTINGS_CHAT               1196
#define IDC_SETTINGS_PM                 1197
#define IDC_OFFCOMPRESS                 1198
#define IDC_SETTINGS_HUB_MENU           1198
#define IDC_SETTINGS_SEARCH_MENU        1200
#define IDC_SETTINGS_CONTEXT            1201
#define IDC_SETTINGS_PARAMETERS         1202
#define IDC_SETTINGS_NAME               1203
#define IDC_SETTINGS_COMMAND            1204
#define IDC_SETTINGS_HUB                1205
#define IDC_SETTINGS_TO                 1206
#define IDC_RESULT                      1207
#define IDC_PREVIEW_BROWSE              1208
#define IDC_REFRESH_FILE_LIST           1210
#define IDC_SEARCH_BY_TTH               1211
#define IDC_SETTINGS_ONCE               1212
#define IDC_OPEN_DOWNLOADS              1213
#define IDC_SETTINGS_UPLOAD_BAR_COLOR   1214
#define IDC_PREVIEW_ARGUMENTS           1214
#define IDC_SETTINGS_DOWNLOAD_BAR_COLOR 1215
#define IDC_PREVIEW_EXTENSION           1215
#define IDC_CHECK1                      1216
#define IDC_Stealth                     1216
#define IDC_STEALTH                     1216
#define IDC_AUTOSEGMENT                 1216
#define IDC_UPDATEIP                    1216
#define IDC_COPY_TTH                    1217
#define IDC_SETTINGS_FORMAT1            1217
#define IDC_EDIT1                       1218
#define IDC_CLIENT_NAME                 1218
#define IDC_SETTINGS_FORMAT2            1218
#define IDC_SEGMENT2_MIN                1219
#define IDC_CLIENT_VERSION              1219
#define IDC_SETTINGS_FORMAT3            1219
#define IDC_COMBOBOXEX1                 1220
#define IDC_SEGMENT2_MAX                1220
#define IDC_CLIENT_TAG                  1220
#define IDC_SETTINGS_FORMAT4            1220
#define IDC_STATIC2                     1221
#define IDC_SEGMENT3_MIN                1221
#define IDC_TOOLBAR_ACTUAL              1221
#define IDC_CLIENT_EXTENDED_TAG         1221
#define IDC_LOG_SYSTEM                  1221
#define IDC_STATIC3                     1222
#define IDC_SEGMENT3_MAX                1222
#define IDC_CLIENT_LOCK                 1222
#define IDC_CHECKa1                     1223
#define IDC_STATIC4                     1223
#define IDC_CLIENT_PK                   1223
#define IDC_MAX_HASH_SPEED              1223
#define IDC_STATIC7                     1224
#define IDC_TOOLBAR_IMAGE               1224
#define IDC_CLIENT_SUPPORTS             1224
#define IDC_CHECK2                      1225
#define IDC_STATICb                     1225
#define IDC_SEGMENT4_MIN                1225
#define IDC_IMAGEBROWSE                 1225
#define IDC_CLIENT_TESTSUR_RESPONSE     1225
#define IDC_SETTINGS_MAX_HASH_SPEED     1225
#define IDC_TOOLBAR_POSSIBLE            1226
#define IDC_CLIENT_USER_CON_COM         1226
#define IDC_SETTINGS_MBS                1226
#define IDC_SIZEBASED                   1227
#define IDC_MOUSE_OVER                  1227
#define IDC_CLIENT_STATUS               1227
#define IDC_NORMAL                      1228
#define IDC_TAG_VERSION                 1228
#define IDC_SEGMENT4_MAX                1229
#define IDC_TOOLBAR_IMAGE_BOX           1229
#define IDC_VERSION_MISMATCH            1229
#define IDC_SEGMENT6_MIN                1230
#define IDC_DOWNLOADDIR_DIR             1230
#define IDC_USE_EXTRA_VERSION           1230
#define IDC_DOWNLOADDIR_NAME            1231
#define IDC_CLIENT_NO_ACTION            1231
#define IDC_SEGMENT8_MIN                1232
#define IDC_DOWNLOADDIR_EXT             1232
#define IDC_CLIENT_RAW_1                1232
#define IDC_CLIENT_ITEMS                1232
#define IDC_DIR_DESCRIPTION             1233
#define IDC_CLIENT_RAW_2                1233
#define IDC_ADD_CLIENT                  1233
#define IDC_SEGMENT2                    1234
#define IDC_CLIENT_RAW_3                1234
#define IDC_CHANGE_CLIENT               1234
#define IDC_SEGMENT3                    1235
#define IDC_CLIENT_RAW_4                1235
#define IDC_MOVE_CLIENT_UP              1235
#define IDC_SEGMENT4                    1236
#define IDC_CLIENT_RAW_5                1236
#define IDC_MOVE_CLIENT_DOWN            1236
#define IDC_SEGMENT6                    1237
#define IDC_REMOVE_CLIENT               1237
#define IDC_SEGMENT8                    1238
#define IDC_ADD_LINE                    1238
#define IDC_USERIP                      1239
#define IDC_SEGMENTWARN                 1240
#define IDC_DONTSEGMENT                 1241
#define IDC_MAX_SEGMENT_SPEED           1242
#define IDC_CLIENT_CHEATING_DESCRIPTION 1243
#define IDC_SEGMENT6_MAX                1244
#define IDC_STATIC8                     1245
#define IDC_MAXCOMPRESS                 1246
#define IDC_MAX_COMPRESSION             1247
#define IDC_MAX_COMP_SPIN               1248
#define IDC_RADIO1                      1249
#define IDC_MAX_SOURCES                 1249
#define IDC_MAX_COMP_SPIN2              1250
#define IDC_RADIO2                      1250
#define IDC_MAX_SOURCES_SPIN            1250
#define IDC_RADIO3                      1251
#define IDC_MAXSOURCES                  1251
#define IDC_MINIMUM                     1252
#define IDC_EXTENSION                   1253
#define IDC_SHUTDOWN_SPIN               1253
#define IDC_KB                          1254
#define IDC_SEG_NUMBER                  1255
#define IDC_SEG_NUMBER_SPIN             1256
#define BAA                             1257
#define CAA                             1258
#define DAA                             1259
#define FAKE_SET                        1260
#define INFORMACE                       1261
#define AAA                             1262
#define IDC_SOUNDLIST                   1263
#define IDC_EMULATION                   1264
#define IDC_CLIENT_EMU                  1265
#define IDC_GETIP                       1266
#define IDC_USERLIST_IMAGE              1267
#define IDC_USERLIST                    1268
#define IDC_IMPORT                      1269
#define IDC_EXPORT                      1270
#define IDC_SETTINGS_GET_USER_COUNTRY	1271
#define IDC_JUNK_VOB_FILE_SIZE          1502
#define IDC_PERCENT_FAKE_SHARE_TOLERATED 1504
#define IDC_TF_OPEN                     1517
#define IDC_TF_OPEN_FOLDER              1518
#define IDC_TF_OPEN_TMP_FOLDER          1519
#define IDC_TF_REMOVE                   1520
#define IDC_SETTINGS_ODC_MENUBAR        1612
#define IDC_SETTINGS_ODC_MENUBAR_USETWO 1613
#define IDC_SETTINGS_ODC_MENUBAR_COLOR  1614
#define IDC_SETTINGS_ODC_MENUBAR2       1615
#define IDC_PROGRESS_COLOR_DOWN_SHOW    1616
#define ahoj                            1616
#define IDC_PROGRESS_COLOR_UP_SHOW      1617
#define IDC_PREVIEW_APP                 1700
#define IDC_TOOLBAR_ADD                 2200
#define IDC_HOTBROWSE                   2201
#define IDC_TOOLBAR_REMOVE              2202
#define IDC_PREVIEW_NAME                2223
#define IDC_PREVIEW_APPLICATION         2224
#define IDC_TOOLBAR_HOT_IMAGE           2224
#define IDC_LIMITER                     2225
#define IDC_BROWSELIST                  3000
#define IDC_REMOVE_SOURCE               3500
#define IDC_PM                          4000
#define IDC_READD                       4500
#define IDC_DOWNLOAD_TARGET             5000
#define IDC_DOWNLOAD_TARGET_DIR         5500
#define IDC_SELECT_WINDOW               6000
#define IDC_USER_COMMAND                6500
#define IDC_PRIORITY_PAUSED             7000
#define IDC_PRIORITY_LOWEST             7001
#define IDC_PRIORITY_LOW                7002
#define IDC_PRIORITY_NORMAL             7003
#define IDC_PRIORITY_HIGH               7004
#define IDC_PRIORITY_HIGHEST            7005
#define IDC_DOWNLOAD_WHOLE_TARGET       7500
#define IDC_REMOVE_SOURCES              8000
#define IDR_TRAY_PM                     10000
#define IDR_TRAY_PM_XP                  10001
#define IDC_EXTRASLOTSSPIN              10002
#define IDC_EXTRA_DOWN_SLOT             10003
#define IDC_EXTRA_DOWNLOADS_MAX         10004
#define IDC_ERROR_COLOR                 10005
#define IDC_UNGRANTSLOT                 10006
#define IDC_UPTIME                      10007
#define IDD_LIMITPAGE                   10008
#define IDC_CZDC_SLOW_DISCONNECT        10009
#define IDC_CZDC_I_DOWN_SPEED           10010
#define IDC_BACK_COLOR                  10011
#define IDC_REMOVE_IF                   10011
#define IDC_BACK_COLOR2                 10012
#define IDC_CZDC_TIME_DOWN              10013
#define IDC_TEXT_STYLE                  10014
#define IDC_TEXT_COLOR                  10015
#define IDC_CZDC_H_DOWN_SPEED           10016
#define IDC_PREVIEW                     10017
#define IDC_CZDC_MIN_FILE_SIZE          10017
#define IDC_I_DOWN_SPEED                10018
#define IDC_TEXT_STYLES                 10019
#define IDC_BLOCK_SIZE                  10019
#define IDC_REMOVE_IF_BELOW             10019
#define IDC_EXTRA_SLOTS                 10020
#define IDC_EXTRA_SLOTS_SPIN            10021
#define IDC_SMALL_FILE_SIZE             10022
#define IDC_SMALL_FILE_SIZE_SPIN        10023
#define IDC_BLACK_AND_WHITE             10024
#define IDC_DEFAULT_STYLES              10025
#define IDC_COPY_TAG                    10026
#define IDC_COPY_FILENAME               10027
#define IDC_COPY_PATH                   10028
#define IDC_TIME_DOWN                   10029
#define IDC_COPY_SIZE                   10030
#define ID_VIEW_TRANSFERS               10031
#define IDC_OPEN_HUB_LOG                10032
#define IDC_OPEN_USER_LOG               10033
#define IDC_H_DOWN_SPEED                10034
#define IDC_SETTINGS_KBPS5              10035
#define IDC_BEEPFILE                    10036
#define IDC_SETTINGS_KBPS7              10036
#define IDC_DOWNLOAD_LOG                10037
#define IDC_DBEGIN                      10037
#define IDC_UPLOADSPEEDSPIN             10038
#define IDC_DFINISHED                   10038
#define IDC_DOWNLOADSPEEDSPIN           10039
#define IDC_SADDED                      10039
#define IDC_BEEPBROWSE                  10040
#define IDD_CZDCPAGE                    10041
#define IDC_BEEPBROWSE2                 10041
#define IDC_NONE                        10041
#define IDD_TEXT_STYLES                 10042
#define IDC_BEEPBROWSE3                 10042
#define IDC_SETTINGS_KBPS6              10043
#define IDC_BEEPBROWSE4                 10043
#define IDD_KICK                        10044
#define IDC_SETTINGS_MB                 10044
#define IDC_UPLOAD_LOG                  10045
#define IDC_SETTINGS_MINUTES            10046
#define IDC_I_DOWN_SPEED_SPIN           10047
#define IDC_TIME_DOWN_SPIN              10048
#define IDC_BEEPBROWSE5                 10048
#define IDC_I_DOWN_SPEED_SPIN2          10048
#define IDC_BLOCK_SIZE_SPIN             10048
#define IDC_H_DOWN_SPEED_SPIN           10049
#define IDC_UFINISHED                   10049
#define IDC_PUBLIC_MESSAGE              10050
#define IDC_MIN_FILE_SIZE_SPIN          10050
#define IDC_BEEPBROWSE6                 10050
#define IDC_SELECT_USER                 10051
#define IDC_UFINISHED2                  10051
#define IDC_FAKERFOUND                  10051
#define IDC_REMOVE_SPIN                 10051
#define IDC_COPY_ACTUAL_LINE            10052
#define IDC_COPY_DESCRIPTION            10053
#define IDC_COPY_EMAIL_ADDRESS          10054
#define IDC_AUTOSCROLL_CHAT             10055
#define IDC_WHOIS_IP                    10056
#define IDC_BAN_IP                      10057
#define IDC_UNBAN_IP                    10058
#define IDC_CLIENT                      10059
#define IDC_COPY_URL                    10060
#define IDC_BOLD_AUTHOR_MESS            10061
#define IDR_ABOUT                       10062
#define IDC_IGNORE                      10063
#define IDC_UNIGNORE                    10064
#define IDC_WINAMP_HELP                 10065
#define IDC_MX_UP_SP_LMT_NORMAL         10069
#define IDC_MX_DW_SP_LMT_NORMAL         10070
#define IDC_MX_UP_SP_LMT_TIME           10071
#define IDC_MX_DW_SP_LMT_TIME           10072
#define IDC_TIME_LIMITING               10073
#define IDC_BW_START_TIME               10074
#define IDC_BW_END_TIME                 10075
#define IDC_UPLOADSPEEDSPIN_TIME        10077
#define IDC_DOWNLOADSPEEDSPIN_TIME      10078
#define IDC_GRANTSLOT_HOUR              10079
#define IDC_GRANTSLOT_DAY               10080
#define IDC_GRANTSLOT_WEEK              10081
#define IDC_UPLOAD_QUEUE                10085
#define IDC_UPLOAD_QUEUE_LIST           10091
#define IDC_THROTTLE_ENABLE             10093
#define IDC_DISCONNECTING_ENABLE        10094
#define IDC_WINAMP                      10095
#define IDC_THROTTLE_ENABLE3            10095
#define IDC_REMOVE_SLOW_USER            10095
#define IDC_READD_ALL_SOURCES           10100
#define IDC_PROGRESS_TEXT_COLOR_DOWN    10102
#define IDC_PROGRESS_TEXT_COLOR_UP      10103
#define IDC_CZDC_FEAT                   10106
#define IDC_CZDC_PM_SOUND               10107
#define IDC_CZDC_TRANSFER_LIMITING      10108
#define IDC_CZDC_UP_SPEEED              10109
#define IDC_CZDC_DW_SPEEED              10110
#define IDC_CZDC_TO                     10111
#define IDC_CZDC_SECONDARY_TRANSFER     10112
#define IDC_CZDC_UP_NOTE                10113
#define IDC_CZDC_DW_NOTE                10114
#define IDC_CZDC_PROGRESS_COLOR         10115
#define IDC_ZDC_PROGRESS_COLOR          10115
#define IDC_CZDC_PROGRESS_TEXT          10117
#define IDC_ZDC_PROGRESS_TEXT           10117
#define IDC_CZDC_WINAMP                 10120
#define IDC_CZDC_AVAILABLE_STYLES       10122
#define IDC_CZDC_PREVIEW                10123
#define IDC_CZDC_DW_SPEEED1             10124
#define IDC_CZDC_UP_SPEEED1             10125
#define IDC_SETTINGS_KBPS1              10126
#define IDC_SETTINGS_KBPS2              10127
#define IDC_SETTINGS_KBPS3              10128
#define IDC_SETTINGS_KBPS4              10129
#define IDC_CZDC_SMALL_SLOTS            10130
#define IDC_CZDC_SMALL_SIZE             10131
#define IDC_CZDC_NOTE_SMALL             10132
#define IDC_ADLSEARCH_SEARCH_STRING     10134
#define IDC_ADLSEARCH_SOURCE_TYPE       10135
#define IDC_ADLSEARCH_DESTINATION_DIRECTORY 10136
#define IDC_ADLSEARCH_MIN_SIZE          10137
#define IDC_ADLSEARCH_MAX_SIZE          10138
#define IDC_ADLSEARCH_SIZE_TYPE         10139
#define IDC_USER_CMD_DESCRIPTION        10140
#define IDC_USER_CMD_EXAMPLE            10141
#define IDC_SETDESCRIPTION              10143
#define IDC_GETLISTFOCUS                10144
#define IDC_COPY_EXACT_SHARE            10145
#define IDC_COPY_IP                     10146
#define IDC_COPY_NICK_IP                10147
#define IDC_COPY_ALL                    10148
#define IDC_COPY_ISP                    10149
#define IDC_CHECKLIST                   10150
#define ID_GET_TTH                      10151
#define IDC_COPY_LINK					10152
#define IDC_BITZI_LOOKUP				20000
#define ID_FILE_CONNECT                 32772
#define ID_FILE_SETTINGS                32774
#define ID_FILE_RECONNECT               32775
#define ID_FILE_SEARCH                  32776
#define IDC_DOWNLOAD                    32780
#define IDC_DOWNLOADTO                  32781
#define IDC_RECENTS                     32782
#define IDC_FAVORITES                   32783
#define IDC_FOLLOW                      32784
#define IDC_SEND_MESSAGE                32786
#define IDC_FILTER_FOCUS                32788
#define IDC_GET_USER_RESPONSES          32789
#define IDC_REPORT                      32790
#define ID_ACCELERATOR32791             32791
#define ID_WINDOW_MINIMIZE_ALL          57654

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        270
#define _APS_NEXT_COMMAND_VALUE         32793
#define _APS_NEXT_CONTROL_VALUE         1273
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
